# Generated by Django 3.2 on 2021-05-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ids',
            name='taken_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
