# Generated by Django 3.2 on 2021-05-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_manager', '0003_alter_ids_taken_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ids',
            name='received_date',
            field=models.DateTimeField(null=True),
        ),
    ]
