# Generated by Django 2.2.10 on 2021-04-16 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='eod',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_day', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_on', models.DateTimeField(null=True)),
                ('days_collections', models.FloatField(default=0.0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=False)),
                ('update_on', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(default=False, null=True)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Branch')),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
