# Generated by Django 3.2 on 2021-04-17 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eod', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eod',
            old_name='transaction_day',
            new_name='transaction_date',
        ),
    ]
