# Generated by Django 2.2.10 on 2020-12-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='injections',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cash_forward', models.FloatField(default=0.0)),
                ('repeat_customers', models.IntegerField(default=0)),
                ('new_customers', models.IntegerField(default=0)),
                ('repeat_customers_amount', models.FloatField(default=0.0)),
                ('new_customers_amount', models.FloatField(default=0.0)),
                ('cash_reserve_need', models.FloatField(default=0.0)),
                ('injection_amount', models.FloatField(default=0.0)),
                ('injection_status', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(verbose_name='date published')),
                ('created_by', models.CharField(max_length=200)),
                ('update_date', models.DateTimeField(verbose_name='date published')),
                ('updated_by', models.CharField(max_length=200)),
            ],
        ),
    ]
