# Generated by Django 3.2 on 2021-05-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='injections',
            name='comment',
            field=models.CharField(default=False, max_length=300),
        ),
    ]
