# Generated by Django 2.2.10 on 2020-12-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201209_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='injections',
            name='injection_authorization',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='injections',
            name='created_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='injections',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='injections',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='injections',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='injections',
            name='updated_by',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
