# Generated by Django 2.2.10 on 2021-03-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_branch_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursements',
            name='id_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
