# Generated by Django 3.2 on 2021-05-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_injections_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rm_collection_sheets',
            name='collected_by',
            field=models.IntegerField(default=False),
        ),
    ]
