# Generated by Django 3.2 on 2021-05-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rm_collection_sheets_collected_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='potential_customers',
            name='other_name',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
