# Generated by Django 3.2 on 2021-05-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_potential_customers_other_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='potential_customers',
            name='loan_count',
            field=models.IntegerField(default=False),
        ),
    ]
