# Generated by Django 2.2.10 on 2021-01-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201229_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injections',
            name='injection_authorization',
            field=models.CharField(default='False', max_length=10),
        ),
    ]
