# Generated by Django 3.2 on 2021-05-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rm_collection_sheets_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rm_collection_sheets',
            name='first_name',
            field=models.CharField(default=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rm_collection_sheets',
            name='last_name',
            field=models.CharField(default=False, max_length=50, null=True),
        ),
    ]
