# Generated by Django 2.2.10 on 2021-01-16 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_profile_rm_daily_activity_rm_weekly_customers_portfolio_targets_collections_disbursement_targets_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Branch'),
        ),
    ]
