# Generated by Django 2.2.10 on 2021-01-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210116_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injections',
            name='updated_by',
            field=models.IntegerField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_by',
            field=models.IntegerField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='rm_daily_activity',
            name='updated_by',
            field=models.IntegerField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='rm_weekly_customers_portfolio',
            name='updated_by',
            field=models.IntegerField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='targets_collections_disbursement',
            name='updated_by',
            field=models.IntegerField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='targets_portfoilo',
            name='updated_by',
            field=models.IntegerField(default=False, null=True),
        ),
    ]
