# Generated by Django 2.2.10 on 2021-01-16 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210116_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='targets_collections_disbursement',
            old_name='Collections',
            new_name='collections',
        ),
        migrations.RenameField(
            model_name='targets_collections_disbursement',
            old_name='Disbursements',
            new_name='disbursements',
        ),
        migrations.RenameField(
            model_name='targets_collections_disbursement',
            old_name='New_Customers',
            new_name='new_customers',
        ),
    ]
