# Generated by Django 3.2 on 2021-06-30 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clusters',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cluster_name', models.CharField(max_length=100, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=False)),
                ('update_on', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cluster_branches',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.branch')),
                ('cluster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clusters.clusters')),
            ],
        ),
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=False)),
                ('update_on', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(default=False, null=True)),
                ('cluster_branch_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clusters.cluster_branches')),
                ('cluster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clusters.clusters')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
